#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-or-later
#
# tests/server/xymongen-alternate-pageset.sh
#
# Behavioural test of xymongen's "alternate pagesets" feature (xymongen.1,
# "BUILDING ALTERNATE PAGESETS", since xymongen 1.4): a second, independent
# page hierarchy built from the *same* status data as the default one, using
# PREFIXpage/PREFIXsubpage/PREFIXgroup directives in hosts.cfg and a
# "PREFIX:pagename" tag on each host to place it -- generated by a separate
# xymongen invocation with --pageset=PREFIX.
#
# Layout (prefix "os"):
#   ospage win         -> Microsoft Windows (no hosts directly on it)
#   ossubpage win-xp    -> MS Windows XP
#
#   normal.example.com    (no OS: tag at all)
#   winxp1.example.com    # OS:win-xp conn
#   winfront.example.com  # OS:* conn
#
# Asserts:
#   - "OS:win-xp" places a host on that subpage, under --pageset=os;
#   - "OS:*" places a host on the pageset's own frontpage instead of any
#     sub/page;
#   - a host with no "OS:" tag at all is not just left on the frontpage by
#     default -- it is absent from the alternate pageset entirely, since the
#     alternate hierarchy is defined purely by these tags, independent of
#     where the host sits in the *default* pageset.

set -euo pipefail
# shellcheck source=tests/lib/assert.sh
. "$(dirname "$0")/../lib/assert.sh"

require_bin XYMONGEN xymongen/xymongen

work=$(mktempdir)
mkdir -p "$work"/ack "$work"/hist "$work"/histlogs "$work"/home/web \
	"$work"/rawstatus "$work"/notes "$work"/rep "$work"/tmp "$work"/var "$work"/web
for f in stdnormal_header stdnormal_footer stdnongreen_header stdnongreen_footer \
	stdcritical_header stdcritical_footer; do
	: > "$work/home/web/$f"
done

cat > "$work/hosts.cfg" <<'EOF'
ospage win Microsoft Windows
ossubpage win-xp MS Windows XP

127.0.0.1 normal.example.com   # conn
127.0.0.1 winxp1.example.com   # OS:win-xp conn
127.0.0.1 winfront.example.com # OS:* conn
EOF

cat > "$work/board.dump" <<'EOF'
normal.example.com|conn|green|||||||127.0.0.1|-1|OK
normal.example.com|info|green|||||||127.0.0.1|-1|Host info
normal.example.com|trends|green|||||||127.0.0.1|-1|Trend graphs
normal.example.com|clientlog|green|||||||127.0.0.1|-1|Client data
winxp1.example.com|conn|green|||||||127.0.0.1|-1|OK
winxp1.example.com|info|green|||||||127.0.0.1|-1|Host info
winxp1.example.com|trends|green|||||||127.0.0.1|-1|Trend graphs
winxp1.example.com|clientlog|green|||||||127.0.0.1|-1|Client data
winfront.example.com|conn|green|||||||127.0.0.1|-1|OK
winfront.example.com|info|green|||||||127.0.0.1|-1|Host info
winfront.example.com|trends|green|||||||127.0.0.1|-1|Trend graphs
winfront.example.com|clientlog|green|||||||127.0.0.1|-1|Client data
EOF

export XYMONACKDIR="$work/ack"
export XYMONHISTDIR="$work/hist"
export XYMONHISTLOGS="$work/histlogs"
export XYMONHOME="$work/home"
export HOSTSCFG="$work/hosts.cfg"
export XYMONRAWSTATUSDIR="$work/rawstatus"
export XYMONLOGSTATUS=DYNAMIC
export XYMONNOTESDIR="$work/notes"
export XYMONREPDIR="$work/rep"
export XYMONREPURL="/rep"
export XYMONSKIN=default
export XYMONTMP="$work/tmp"
export XYMONVAR="$work/var"
export XYMONWEB="$work/web"
export XYMONWWWDIR="$work/web"
export XYMONWEBHOST="http://localhost"
export XYMONWEBHOSTURL=""
export CGIBINURL="/cgi-bin"
export DOTHEIGHT=16
export DOTWIDTH=16
export MACHINE=localhost
export MACHINEADDR=127.0.0.1
export XYMONPAGECOLFONT=""
export XYMONPAGELOCAL=""
export XYMONPAGESUBLOCAL=""
export XYMONPAGEREMOTE=""
export XYMONPAGEROWFONT=""
export XYMONPAGETITLE="Test"
export PURPLEDELAY=0
export BOARDDUMP="$work/board.dump"

"$XYMONGEN" --pageset=os >"$work/xymongen.out" 2>"$work/xymongen.err" || {
	cat "$work/xymongen.out" >&2
	cat "$work/xymongen.err" >&2
	fail "xymongen --pageset=os exited non-zero"
}

assert_file_exists "$work/web/xymon.html" "pageset frontpage was not generated"
assert_file_exists "$work/web/win/win.html" "pageset 'win' page was not generated"
assert_file_exists "$work/web/win/win-xp/win-xp.html" "pageset 'win-xp' subpage was not generated"

front=$(cat "$work/web/xymon.html")
win=$(cat "$work/web/win/win.html")
winxp=$(cat "$work/web/win/win-xp/win-xp.html")

assert_contains 'winfront.example.com' "$front" \
	"'OS:*' must place the host on the pageset's own frontpage"
assert_not_contains 'normal.example.com' "$front" \
	"a host with no OS: tag must not default onto the pageset frontpage"
assert_not_contains 'winxp1.example.com' "$front" \
	"'OS:win-xp' must not also leave the host on the frontpage"

assert_contains 'winxp1.example.com' "$winxp" "'OS:win-xp' must place the host on the win-xp subpage"
assert_not_contains 'normal.example.com' "$winxp" "an untagged host must not appear on win-xp either"

assert_not_contains 'normal.example.com' "$win" \
	"an untagged host must not appear anywhere in the alternate pageset"

pass "xymongen alternate pageset (--pageset=) places hosts by their OS: tag only"
